version: '3.8'
services:
  backend:
    build: ./backend
    env_file:
      - ../.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
  frontend:
    build: ./frontend
    env_file:
      - ../.env
    ports:
      - "3000:3000"
    depends_on:
      - backend